### ISSUE TITLE
Purpose of the caching?

### ISSUE THREAD

**Issue by tocr** [auth0/angular-storage#27]
I wanted to ask about the purpose of the internal storage caching. Is it due to the performance reasons?

I am using the store for keeping the jwt token.
I wanted to test the jwt token being tampered by manually altering the token in the browser's localStorage.
I was surprised that the subsequent request came from the server with 200 OK.

It was caused by the internally cached value in the store.

Isn't this default behavior a bit confusing? IMO it would be nice to have the caching functionality switchable via the provider configuration.

**Comment by mgonto** [comment]
You're right. This should be a feature that could be activated and deactivated via the Provider.

However, I think it's good to leave it activated by default. For performance, it's much quicker otherwise, we have to do `JSON.parse` and `JSON.stringify` often which are costly operations.

The cached is explain as one of the key features of this library.

Are you willing to send a PR with the config added?

Thanks!

**Comment by tocr** [comment]
OK, I will try to prepare the pull request

Thank you

**Comment by sunieldalal** [comment]
any updates on this issue? I want to disable the caching so that i can get the latest value from the store..

**Comment by igorissen** [comment]
Hope this update can be there for the next version.

**Comment by loverzpark** [comment]
May i disable cache ? if yes, how? if not , let me know how i will get un-cached or fresh value instead cache ?

**Comment by flyingfisher** [comment]
If multi-window is opened, and use 'local-storage' as storage. Value in cache will be dirty. I do not think this is an enhancement.

**Comment by sakopov** [comment]
Running into the same issue that @flyingfisher is reporting. If two windows are open the JWT will be cached and used in one window even after removing token from local storage and logging out from the other window. This should be revisited as a bug.

**Comment by JoernBerkefeld** [comment]
more importantly, optionally skipping the cache could EASILY be exposed via an extra variable in the getter.

**Comment by frankhock** [comment]
looking like this is working? `storeProvider.setCaching(false)`
