### ISSUE TITLE
Proper handling of localStorage disabled check

### ISSUE THREAD

**Issue by ako977** [auth0/angular-storage#30]
In angular-storage on line 86 a check is performed for localStorage enabled on the browser by 

    var localStorageAvailable = !!$window.localStorage;

This check is not adequate enough bc/ at least in chrome, you get an error: 
    Error: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
I recommend removing that line and rather just using the try catch that is performed below as: 
      
    try {
        $window.localStorage.setItem('testKey', 'test');
        $window.localStorage.removeItem('testKey');
        var localStorageAvailable = true;
      } catch(e) {
        var localStorageAvailable = false;
    }

This way chrome wouldn't break the script on the site.
This code executes before any other check in other app modules can mitigate this (for angularjs apps with localStorage turned off) This would be in order to even show a warning notice to the user.

**Comment by mgonto** [comment]
This is already implemented in the latest version of Angular Stoarge.

Check [this](https://github.com/auth0/angular-storage/blob/master/dist/angular-storage.js#L88-L96)

Thanks!

**Comment by mgonto** [comment]
Ohhh you mean the first line throws therefore it never gets to the below one.

We jsut need to change [this line](https://github.com/auth0/angular-storage/blob/master/dist/angular-storage.js#L86) and delete the if down.

Are you willing to PR this?

Thanks!

**Comment by ako977** [comment]
Hi Martin,

Yeah I can do that.

**Comment by ako977** [comment]
Hi, just let me know when I have pull request access and I will make one.
Thanks

**Comment by mgonto** [comment]
Pull request is always open. Just fork the repository and then do a pull request to it :).

**Comment by ako977** [comment]
Thanks, I've made the pull request

**Comment by jercoh** [comment]
Hi, I've made another pull request to handle sessionStorage check as well. I was getting an error in Chrome.
