### ISSUE TITLE
No way to clear localStorage

### ISSUE THREAD

**Issue by notduncansmith** [auth0/angular-storage#33]
We're currently using this workaround:

```
store.clear = function() {
  window.localStorage.clear();
};
```

But it would be awesome if this were supported in the library.  Thanks!

**Comment by mgonto** [comment]
Hey,

Are you willing to PR this :)?

Thanks!

**Comment by notduncansmith** [comment]
I was hoping to see tests passing first (see #32) but yes I can PR this.

**Comment by miguelchico** [comment]
Hi

I created / rescued a PR to include clear operation.
https://github.com/auth0/angular-storage/pull/58
