### ISSUE TITLE
Outdated README?

### ISSUE THREAD

**Issue by rictorres** [auth0/angular-storage#34]
Hey, @mgonto 
Great work on this module :)

I was following the discussion on https://github.com/auth0/angular-storage/issues/19, https://github.com/auth0/angular-storage/pull/20 and going through https://github.com/auth0/angular-storage/commit/a8588c0578d565482f2225b8d314b7de6862e457 changes.

Correct me if I'm wrong but it seems that the README was not updated to reflect those changes.

What do you think?

**Comment by mgonto** [comment]
You're right :). Wanna PR it :)?

Thanks!

**Comment by rictorres** [comment]
Sure ;)
