### ISSUE TITLE
Clear all

### ISSUE THREAD

**Issue by danielfpedro** [auth0/angular-storage#39]
In my case, I have a lot of keys stored and on logout I just need remove all of then.

**Comment by igorissen** [comment]
Agree. I hope it will be in the next version.

**Comment by gauravarora** [comment]
+1

**Comment by ruizalvaro** [comment]
+1

**Comment by JackLeo** [comment]
One of the more popular libraries for this is probably ngStorage. They have pretty well defined interaction for this: https://github.com/gsklee/ngStorage#delete-everything--demo

**Comment by seanlindo** [comment]
Are you all still looking for this? I wouldn't mind making a pull request this week to address it.

**Comment by graham-sportsmgmt** [comment]
I'm looking for this too.  Optimally I'd like to be able to specify a key regexp for matching what I want to clear.

**Comment by miguelchico** [comment]
Hi @all,

I created a pull request for that
https://github.com/auth0/angular-storage/pull/58
