### ISSUE TITLE
Unable to fetch String based cookies cause CookieStore is deprecated

### ISSUE THREAD

**Issue by robin-maxxton** [auth0/angular-storage#41]
First of all. Good job on creating this library.

I do have one suggestion.
While using the library I was unable to fetch a String based cookie from my list of cookies.
The library wanted to have an cookie that was JSON based, but because my Sting based cookie was not set by using the library (set from a response header), it failed.

It seems the **$cookieStorage** is using Angular's **$cookieStore**.
According to the Angular documentation this is a **deprecated** service.
https://docs.angularjs.org/api/ngCookies/service/$cookieStore
You should use the $cookies service instead.
Please consider changing services to support the use of non JSON bases cookies.
Thanks in advance.

**Comment by tyoungjr** [comment]
Create a PR for this https://github.com/auth0/angular-storage/pull/46 , in the mean time you can replace that module locally like this, 
```javascript
angular.module('angular-storage.cookieStorage', ['ngCookies'])
  .service('cookieStorage', ["$cookies", function ($cookies) {

    this.set = function (what, value) {
      return $cookies.put(what, value);
    };

    this.get = function (what) {
      return $cookies.get(what);
    };

    this.remove = function (what) {
      return $cookies.remove(what);
    };
  }]);
```

**Comment by ebourmalo** [comment]
:+1:
