### ISSUE TITLE
Usage in config phase

### ISSUE THREAD

**Issue by kikar** [auth0/angular-storage#43]
How do I access the storage in a .config function?

**Comment by rjgoldsborough** [comment]
I'm also curious about this. I would like to use the angular-storage module with the other auth0 module angular-jwt. I would like to check for the token in storage in conjunction with the jwtInterceptorProvider in the config block.

**Comment by rjgoldsborough** [comment]
Huh, not sure what I was doing before but https://github.com/auth0/angularjs-jwt-authentication-tutorial/blob/4-sending-jwt-on-requests/frontend/app.js#L10 seems to work just fine.

**Comment by vlapo** [comment]
+1

**Comment by wootencl** [comment]
If you look at the README (specifically the [FAQ](https://github.com/auth0/angular-jwt#faq)) this is covered.
