### ISSUE TITLE
Multiple storages

### ISSUE THREAD

**Issue by kikar** [auth0/angular-storage#44]
Can I use both sessionStorage and localStorage at the same time? For example if user checks the 'Remind me' button, I would want to use localStorage, but I don't know that before…

**Comment by marcokorb** [comment]
+1

**Comment by SkydiverFL** [comment]
+1

**Comment by SkydiverFL** [comment]
Looks like this may have been addressed on Feb 24, 2015 by @mgonto for item #19 .  Based on his response, the following syntax should allow multiple namespaced stores to be created, each with a specific storage mechanism.

.factory('StoreA', function(store) {
  return store.getNamespacedStore('storeA', 'sessionStorage');
})
.factory('StoreB', function(store) {
  return store.getNamespacedStore('storeB', 'localStorage');
})

**Comment by ivanzvakoms** [comment]
this should be added to documentation readme.md
