### ISSUE TITLE
JWT token saved with quotes

### ISSUE THREAD

**Issue by Fossil01** [auth0/angular-storage#60]
```javascript
store.set('jwt', response.data.token);
```

This stores the token value encapsulated in quotes. Is there any way to avoid this? I just want the plain output from `response.data.token` which is unquoted.

**Comment by hexadecy** [comment]
Any workaround?

**Comment by vaail** [comment]
@Fossil01 @hexadecy 
Use **store.get('jwt')** in **tokenGetter**.
